const assert=require("node:assert/strict");
const k=require("../assets/knowledge-pipeline.js");
const s=k.normalizeSource({id:"s1",title:"Paper",url:"https://example.org/paper",topicIds:["ai","ai"],primary:true});
assert.equal(s.primary,true);
assert.deepEqual(s.topicIds,["ai"]);
assert.throws(()=>k.normalizeSource({id:"s2",title:"No URL",url:"javascript:alert(1)"}));
const c=k.makeCluster({id:"c1",topicId:"ai",sourceIds:["s1","s1","s2"]});
assert.deepEqual(c.sourceIds,["s1","s2"]);
assert.equal(c.state,"provisional");
let n=k.proposeNucleus({id:"n1",topicId:"ai",question:"Are benchmarks reliable?",clusterIds:["c1"],reason:"Repeated independent coverage"});
assert.equal(n.debate,"disabled");
assert.throws(()=>k.enableDebate(n));
n=k.transitionNucleus(n,"reviewed");
n=k.transitionNucleus(n,"published");
n=k.enableDebate(n);
assert.equal(n.debate,"enabled");
assert.deepEqual(k.linkCluster(n,{id:"c2",topicId:"ai"}).clusterIds,["c1","c2"]);
assert.throws(()=>k.linkCluster(n,{id:"c3",topicId:"war"}));
assert.throws(()=>k.transitionNucleus(n,"candidate"));
assert.equal(k.transitionNucleus(n,"archived").state,"archived");
console.log("Knowledge pipeline contract checks passed");
