-- Ubik canonical event store v1
create table if not exists public.events (
  id text primary key,
  occurred_at timestamptz not null,
  country_code text not null default 'UA',
  place text not null,
  region text,
  latitude double precision not null,
  longitude double precision not null,
  event_type text not null,
  target_type text,
  actor text,
  weapon text,
  summary text,
  status text not null default 'signal' check (status in ('signal','reported','corroborated','documented','disputed','validated')),
  fatalities integer,
  injuries integer,
  control_status text,
  confidence real,
  fingerprint text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists events_occurred_at_idx on public.events (occurred_at desc);
create index if not exists events_region_idx on public.events (region);
create index if not exists events_geo_idx on public.events (latitude,longitude);
create index if not exists events_fingerprint_idx on public.events (fingerprint);

create table if not exists public.event_sources (
  id bigint generated by default as identity primary key,
  event_id text not null references public.events(id) on delete cascade,
  publisher text,
  url text,
  origin_id text,
  published_at timestamptz,
  source_type text,
  created_at timestamptz not null default now(),
  unique(event_id,url)
);
create index if not exists event_sources_event_idx on public.event_sources(event_id);

create table if not exists public.ingestion_runs (
  id bigint generated by default as identity primary key,
  adapter text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  input_count integer default 0,
  inserted_count integer default 0,
  merged_count integer default 0,
  rejected_count integer default 0,
  metadata jsonb default '{}'::jsonb
);

-- API queries should request only the visible map viewport and/or one archive page.
-- Occupation/control is metadata/layer logic, not a change to Ukraine's state boundary.
